import { requireSession } from "@/lib/auth/session";
import { getBillingDashboard } from "@/lib/billing-service";
import { money } from "@/lib/billing";

const statusName: Record<string, string> = { trial: "Período de teste", pending: "Aguardando pagamento", active: "Ativa", past_due: "Pagamento atrasado", suspended: "Suspensa", cancelled: "Cancelada", confirmed: "Confirmado", received: "Recebido", overdue: "Vencido", refunded: "Estornado" };

export default async function BillingPage({ searchParams }: { searchParams: Promise<{ created?: string; error?: string }> }) {
  const session = await requireSession();
  const data = await getBillingDashboard(session.organizationId);
  const query = await searchParams;
  return <main className="billing-page">
    <header><div><a href="/dashboard">← Visão geral</a><small>PLANO E COBRANÇA</small><h1>Assinatura de {session.organizationName}</h1><p>Recorrência automática em ambiente sandbox, sem cobrança real nesta etapa.</p></div></header>
    {query.created && <p className="billing-alert success">Assinatura sandbox criada. O trial termina em 14 dias.</p>}
    {query.error && <p className="billing-alert error">Não foi possível criar a assinatura. {query.error === 'config' ? 'As credenciais sandbox ainda não foram configuradas.' : 'Revise os dados e tente novamente.'}</p>}
    {data.current ? <section className="current-plan"><div><small>PLANO ATUAL</small><h2>{data.current.plan.name}</h2><p>{statusName[data.current.subscription.status] ?? data.current.subscription.status}</p></div><div><b>{money(data.current.plan.priceCents)}</b><span>por mês · {data.current.subscription.billingType}</span>{data.current.subscription.trialEndsAt && <span>Trial até {data.current.subscription.trialEndsAt.toLocaleDateString('pt-BR')}</span>}</div></section> : <section className="billing-intro"><small>COMECE SEM COBRANÇA IMEDIATA</small><h2>14 dias para testar. Depois, recorrência automática.</h2><p>O Asaas emite e acompanha as cobranças. O TapLink reage aos webhooks e nunca considera uma assinatura criada como pagamento recebido.</p></section>}
    <section className="plan-grid">{data.plans.map(plan => { const limits = JSON.parse(plan.limitsJson) as { plates: number; users: number; ai: boolean }; return <article className={plan.code === 'negocios' ? 'featured' : ''} key={plan.id}><small>{plan.code === 'negocios' ? 'RECOMENDADO' : 'PLANO'}</small><h2>{plan.name}</h2><b>{money(plan.priceCents)}<em>/mês</em></b><ul><li>Até {limits.plates} placas</li><li>{limits.users} usuários</li><li>{limits.ai ? 'IA opcional disponível' : 'Relatórios determinísticos'}</li></ul><a href={`#contratar-${plan.code}`}>Escolher</a></article> })}</section>
    {session.role === 'owner' && <section className="subscribe-card"><div><small>CONTRATAÇÃO SANDBOX</small><h2>Dados do responsável financeiro</h2><p>CPF/CNPJ e contato são enviados diretamente ao Asaas para criar o pagador. Não armazenamos esses dados no banco do TapLink nesta versão.</p></div><form action="/api/billing/subscribe" method="post"><label>Plano<select name="plan" required>{data.plans.map(plan => <option value={plan.code} key={plan.id}>{plan.name} — {money(plan.priceCents)}</option>)}</select></label><label>Nome ou razão social<input name="name" required minLength={3} maxLength={120} /></label><label>CPF ou CNPJ<input name="cpfCnpj" required inputMode="numeric" /></label><label>E-mail financeiro<input name="email" required type="email" /></label><label>Celular<input name="phone" inputMode="tel" /></label><label>Forma de cobrança<select name="billingType"><option value="PIX">Pix</option><option value="BOLETO">Boleto</option></select></label><button>Criar assinatura sandbox</button></form></section>}
    <section className="payment-history"><small>HISTÓRICO</small><h2>Cobranças recebidas por webhook</h2>{data.payments.length ? data.payments.map(payment => <div key={payment.id}><span><b>{statusName[payment.status] ?? payment.status}</b><small>{payment.dueDate?.toLocaleDateString('pt-BR') ?? 'Sem vencimento'}</small></span><strong>{money(payment.valueCents)}</strong>{payment.invoiceUrl && <a href={payment.invoiceUrl} target="_blank" rel="noreferrer">Abrir fatura</a>}</div>) : <p>Nenhuma cobrança sincronizada ainda.</p>}</section>
    <footer>A inadimplência altera o estado administrativo e inicia uma régua de tratamento. A página pública e os dados não são apagados automaticamente.</footer>
  </main>;
}
