import { eq } from "drizzle-orm";
import { z } from "zod";
import { getSessionContext } from "@/lib/auth/session";
import { inspectAsaasSubscription } from "@/lib/asaas";
import { validCsrf } from "@/lib/security";
import { db } from "@/packages/database/client";
import { auditLogs, billingPayments, billingPlans, organizations, organizationSubscriptions } from "@/packages/database/schema";
const schema=z.object({organizationId:z.uuid(),confirmation:z.string().trim().max(80)});
export async function POST(request:Request){const actor=await getSessionContext();if(!actor||actor.platformRole!=="platform_admin")return Response.json({error:"Acesso administrativo necessário."},{status:403});const form=await request.formData().catch(()=>new FormData());if(!validCsrf(request,actor.sessionTokenHash,form.get("csrf")))return Response.json({error:"Validação de segurança expirada."},{status:403});const parsed=schema.safeParse(Object.fromEntries(form));if(!parsed.success)return Response.redirect(new URL("/admin/reconciliation?error=dados",request.url),303);const[row]=await db.select({organization:organizations,subscription:organizationSubscriptions,plan:billingPlans}).from(organizations).innerJoin(organizationSubscriptions,eq(organizationSubscriptions.organizationId,organizations.id)).innerJoin(billingPlans,eq(billingPlans.id,organizationSubscriptions.planId)).where(eq(organizations.id,parsed.data.organizationId)).limit(1);if(!row||row.organization.slug!==parsed.data.confirmation||!row.subscription.providerSubscriptionId)return Response.redirect(new URL("/admin/reconciliation?error=confirmação",request.url),303);try{const remote=await inspectAsaasSubscription(row.subscription.providerSubscriptionId);const localPayments=await db.select({providerPaymentId:billingPayments.providerPaymentId,status:billingPayments.status}).from(billingPayments).where(eq(billingPayments.subscriptionId,row.subscription.id));const remoteIds=new Set(remote.payments.map(payment=>String(payment.id??"")));const missingLocal=remote.payments.filter(payment=>!localPayments.some(local=>local.providerPaymentId===payment.id)).length;const missingRemote=localPayments.filter(local=>!remoteIds.has(local.providerPaymentId)).length;await db.insert(auditLogs).values({organizationId:row.organization.id,actorUserId:actor.userId,action:"platform.billing.reconciled",entityType:"organization_subscription",entityId:row.subscription.id,metadataJson:JSON.stringify({environment:"sandbox",localStatus:row.subscription.status,remoteStatus:remote.subscription.status??null,localPlanValueCents:row.plan.priceCents,remoteValue:remote.subscription.value??null,localPayments:localPayments.length,remotePayments:remote.payments.length,missingLocal,missingRemote,mutated:false})});return Response.redirect(new URL("/admin/reconciliation?checked=1",request.url),303)}catch(error){const code=error instanceof Error?error.message:"UNKNOWN";return Response.redirect(new URL(`/admin/reconciliation?error=${encodeURIComponent(code)}`,request.url),303)}}
